window:
  padding:
    x: 2
    y: 2

  decorations: none

  opacity: 0.9

font:
  normal:
    family: "UbuntuMono Nerd Font"
    style: "Regular"
  bold:
    family: "UbuntuMono Nerd Font"
    style: "Bold"
  italic:
    family: "UbuntuMono Nerd Font"
    style: "Regular Italic"
  bold_italic:
    family: "UbuntuMono Nerd Font"
    style: "Bold Italic"

  size: 14.0

  offset:
    y: 2

colors:
  # Default colors
  primary:
    background: "0xffffff"
    foreground: "0x24292f"

  # Normal colors
  normal:
    black: "0x24292e"
    red: "0xd73a49"
    green: "0x28a745"
    yellow: "0xdbab09"
    blue: "0x0366d6"
    magenta: "0x5a32a3"
    cyan: "0x0598bc"
    white: "0x6a737d"

  # Bright colors
  bright:
    black: "0x959da5"
    red: "0xcb2431"
    green: "0x22863a"
    yellow: "0xb08800"
    blue: "0x005cc5"
    magenta: "0x5a32a3"
    cyan: "0x3192aa"
    white: "0xd1d5da"

  indexed_colors:
    - { index: 16, color: "0xd18616" }
    - { index: 17, color: "0xcb2431" }
